global:
    ros__parameters:
        # [latitude, longitude, altitude]
        # datum: [51.937587, 5.705458, 53.801823] # Randwijck
        datum: [51.987305, 5.663625, 53.801823] # Wageningen
        max_distance: 20.0
        min_distance: 10.0
        num_robots: 3

        # or use the following to specify the initial poses of the robots
        robots:
            - namespace: robot0
              initial_pose:
                  latitude: 51.93778674075392
                  longitude: 5.70576672207017
                  altitude: 53.80182320303043
                  heading: 45.0
            - namespace: robot1
              initial_pose:
                  latitude: 51.93724974075392
                  longitude: 5.70526372207017
                  altitude: 53.80182320303043
                  heading: 135.0
            - namespace: robot2
              initial_pose:
                  latitude: 51.93704974075392
                  longitude: 5.70506372207017
                  altitude: 53.80182320303043
                  heading: 135.0
